//This is WIP, not being used right now. 

node{
	//todo - Store port to Device type in map, after all bugs are fixed. 
	def remoteHost
	def remoteUser
	def baseDir
	def branch
	def checkoutNeeded=true;
	def stringParams=['remoteHost','remoteUser','baseDir','branch','projectName']

	
	stage ('Parse Params')
	{
                   echo this.params.toString()



	
		  if(this.params.checkoutNeeded!=null)
                        {
                                checkoutNeeded=this.params.checkoutNeeded;
                        }
	}

	stage ('Checkout'){
		if(checkoutNeeded)
		{

			checkout([$class: 'GitSCM',branches: [[name: branch]],userRemoteConfigs: [[credentialsId: 'deployjava', url: 'git@gitlab.com:axestrack_bankend/gps-kafka-consumer.git']]])
		}
	}

	stage ('Build'){
		echo "Building listener..."
			sh "ls -la ${pwd()}"
			sh "ls -la ."
			sh "pwd"
			retVal=sh(returnStatus: true,script:"sh ./build.sh")
			echo "Build returned ${retVal.toString()}"
			if (retVal!=0)
			{
				error("Build failed with return value ${retVal.toString()}") 
			}	
		echo "Finished building...."

	}
	stage('SSH transfer and restart') {


	}
}

