#!/bin/bash

username=`whoami`

# Update the folders
source_folder="/disk4/backups/postgresql/data/20221121/"
destination_folder="/var/lib/postgresql/12/main"

# Update the IP here
remote="postgres@107.6.150.90"

if [ $username != "postgres" ]; then
   echo "This script must be run as postgres" 
   exit 1
else
   echo "Source Folder: $source_folder"
   echo "Destination Folder: $destination_folder"
   rsync -rt $source_folder postgres@107.6.150.90:$destination_folder
   sleep 10
   echo "* Running commands on remote host named $remote *"
   echo
   ssh -T $remote <<'EOL'
##################### Update the Commands for Remote server
        name="$HOSTNAME"
        echo "Server Name for remote script is $name"


        sudo systemctl start postgresql.service
EOL
fi

